[package]
name = "state-processor"
version = "0.1.0"
edition = "2024"

[lib]
name="state_processor"
crate-type=["cdylib"]

[dependencies]
more-asserts = "0.3.1"
noise = "0.9.0"
pyo3 = { version = "0.27.1", features = ["extension-module"]}
rand = "0.9.2"
